# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b22f39636576dc845326fe746746bdde1c2d43fee699226d5ae1a233fdae325a269752184a3c6bcd945e288d14b654342769c41865c64afa283e40c095413f

test:
  secret_key_base: c42f46f0bd5ed788eff70aa33c82dbf74fa3ef6230c249fd6f7c70af7a869c9066c68e08c04c57579d9fcce4c725ac8060c75bf1c7edb8b5bd74ee350e65e449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
